name: Amplify-react Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-npm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm install
    - run: touch ./src/aws-exports.js
    - run: CI=false npm run build --if-present


  build-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        touch ./src/aws-exports.js
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)